# Generated by Django 6.0.4 on 2026-06-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
